<?php
/**
 * Writes config.php and <admin>/config.php from the environment. Run by
 * setup.sh on every `docker compose up`, so the URL, back office directory,
 * database credentials and storage path always follow the environment.
 * Storage lives outside the web root (/var/www/storage), as OpenCart's own
 * security check recommends.
 *
 * Usage: php conf.php <code dir> <admin dir name>
 */

[, $code, $admin] = $argv;
$code = rtrim($code, '/') . '/';
$url = rtrim((string) getenv('OC_URL'), '/') . '/';
$q = static fn (string $value): string => var_export($value, true);

$db = "// DB\n"
    . "define('DB_DRIVER', 'mysqli');\n"
    . 'define(\'DB_HOSTNAME\', ' . $q((string) getenv('DB_HOST')) . ");\n"
    . 'define(\'DB_USERNAME\', ' . $q((string) getenv('DB_USER')) . ");\n"
    . 'define(\'DB_PASSWORD\', ' . $q((string) getenv('DB_PASSWORD')) . ");\n"
    . 'define(\'DB_DATABASE\', ' . $q((string) getenv('DB_NAME')) . ");\n"
    . "define('DB_PREFIX', 'oc_');\n"
    . 'define(\'DB_PORT\', ' . $q((string) getenv('DB_PORT')) . ");\n\n"
    . "// Cache\n"
    . "define('CACHE_ENGINE', 'file');\n";

$dirs = static fn (string $application): string => "// DIR\n"
    . 'define(\'DIR_OPENCART\', ' . $q($code) . ");\n"
    . "define('DIR_APPLICATION', DIR_OPENCART . " . $q($application) . ");\n"
    . "define('DIR_SYSTEM', DIR_OPENCART . 'system/');\n"
    . "define('DIR_EXTENSION', DIR_OPENCART . 'extension/');\n"
    . "define('DIR_IMAGE', DIR_OPENCART . 'image/');\n"
    . "define('DIR_STORAGE', '/var/www/storage/');\n"
    . ($application !== 'catalog/' ? "define('DIR_CATALOG', DIR_OPENCART . 'catalog/');\n" : '')
    . "define('DIR_LANGUAGE', DIR_APPLICATION . 'language/');\n"
    . "define('DIR_TEMPLATE', DIR_APPLICATION . 'view/template/');\n"
    . "define('DIR_CONFIG', DIR_SYSTEM . 'config/');\n"
    . "define('DIR_CACHE', DIR_STORAGE . 'cache/');\n"
    . "define('DIR_DOWNLOAD', DIR_STORAGE . 'download/');\n"
    . "define('DIR_LOGS', DIR_STORAGE . 'logs/');\n"
    . "define('DIR_SESSION', DIR_STORAGE . 'session/');\n"
    . "define('DIR_UPLOAD', DIR_STORAGE . 'upload/');\n\n";

$header = "<?php\n// Generated by the stack's scripts/conf.php on every `docker compose up`.\n"
    . "// Edit the environment (.env), not this file.\n\n";

$files = [
    $code . 'config.php' => $header
        . "// APPLICATION\ndefine('APPLICATION', 'Catalog');\n\n"
        . "// HTTP\ndefine('HTTP_SERVER', " . $q($url) . ");\n\n"
        . $dirs('catalog/') . $db,
    $code . $admin . '/config.php' => $header
        . "// APPLICATION\ndefine('APPLICATION', 'Admin');\n\n"
        . "// HTTP\ndefine('HTTP_SERVER', " . $q($url . $admin . '/') . ");\n"
        . 'define(\'HTTP_CATALOG\', ' . $q($url) . ");\n\n"
        . $dirs($admin . '/') . $db
        . "\n// OpenCart API\ndefine('OPENCART_SERVER', 'https://www.opencart.com/');\n",
];

foreach ($files as $file => $php) {
    if (!is_file($file) || file_get_contents($file) !== $php) {
        if (is_file($file)) {
            chmod($file, 0600);
        }
        file_put_contents($file, $php);
        echo '    ' . substr($file, strlen($code)) . " updated\n";
    }
    chmod($file, 0400);
}
